#ifndef __fsl_port_h
#define __fsl_port_h

#include "FSL_COMMON.H"

/*GPIO CLK*/
#define __SIM_PORTA_CLK_ENABLE()	SIM_SCGC5_REG(SIM) |= SIM_SCGC5_PORTA_MASK
#define __SIM_PORTB_CLK_ENABLE()	SIM_SCGC5_REG(SIM) |= SIM_SCGC5_PORTB_MASK
#define __SIM_PORTC_CLK_ENABLE()	SIM_SCGC5_REG(SIM) |= SIM_SCGC5_PORTC_MASK
#define __SIM_PORTD_CLK_ENABLE()	SIM_SCGC5_REG(SIM) |= SIM_SCGC5_PORTD_MASK
#define __SIM_PORTE_CLK_ENABLE()	SIM_SCGC5_REG(SIM) |= SIM_SCGC5_PORTE_MASK

/*UART CLK*/
#define __SIM_UART0_CLK_ENABLE()    SIM_SCGC4_REG(SIM) |= SIM_SCGC4_UART0_MASK
#define __SIM_UART1_CLK_ENABLE()    SIM_SCGC4_REG(SIM) |= SIM_SCGC4_UART1_MASK
#define __SIM_UART2_CLK_ENABLE()    SIM_SCGC4_REG(SIM) |= SIM_SCGC4_UART2_MASK




uint8_t     port_init   (PORT_Type *PORTn,uint32_t pin,uint16_t ALTn);

#endif
